import "./globals.css";
import type { Metadata } from "next";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { cookies } from "next/headers";
// import { refreshTokenStore } from "@/stores/useRefreshTokenDataStore";
import { CookieProvider } from "@/providers/CookieContext";
// import { useCookieStore } from "@/store/cookieStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const ssrCookie = cookieStore.get("refreshToken");
  const cookieValue = ssrCookie?.value
    ? JSON.parse(ssrCookie.value)
    : undefined;

  // console.log(
  //   "refreshToken cookie in layout =============================>>>:",
  //   cookieValue?.refreshToken
  // );

  // const { refreshToken, setRefreshToken } = refreshTokenStore();
  // setRefreshToken(cookieValue?.refreshToken);
  // console.log("refreshToken in layout", refreshToken);

// with zustand 
// useCookieStore.setState({ cookie: cookieValue });

  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <QueryClientProvider>
          {/* <DisableWorkbox /> */}
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <CookieProvider initialCookie={cookieValue?.refreshToken}>
          {children}
          </CookieProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
