import "./globals.css";
import type { Metadata } from "next";
import QueryClientProvider from "@/providers/QueryClientProvider";
import RefreshTokenInitializer from "@/providers/RefreshTokenInitializer";
// import { CookieContextProvider } from "@/providers/CookieContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <QueryClientProvider>
          {/* <DisableWorkbox /> */}
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <RefreshTokenInitializer  />
          {/* <CookieContextProvider> */}
            {children}
            {/* </CookieContextProvider> */}
        </QueryClientProvider>
      </body>
    </html>
  );
}
