import "./globals.css";
import type { Metadata } from "next";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { cookies } from "next/headers";
import { refreshTokenStore } from "@/stores/useRefreshTokenDataStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const ssrCookie = cookieStore.get("refreshToken");
  const cookieValue = ssrCookie?.value
    ? JSON.parse(ssrCookie.value)
    : undefined;

  // console.log(
  //   "refreshToken cookie in layout =============================>>>:",
  //   cookieValue?.refreshToken
  // );

  const { refreshToken, setRefreshToken } = refreshTokenStore();
  setRefreshToken(cookieValue?.refreshToken);
  console.log(
    "next/headers get by refreshToken so set in layout by zusatand",
    refreshToken
  );

  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <QueryClientProvider>
          {/* <DisableWorkbox /> */}
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
